source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'


use_frameworks!

target 'Sport' do
	project 'Sport.xcodeproj'
    pod 'RealmSwift' #,'<= 1.0.1'
    pod 'MBProgressHUD'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'MBCircularProgressBar' #,'<= 0.3.4'
    #pod 'SnapKit' #,'~> 0.22.0'
    #pod 'AudioKit', '~> 3.5'
end
